"""Added aidrequest model

Revision ID: 517fec185d45
Revises: 6e167aed2b8c
Create Date: 2026-06-11 16:47:09.834037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517fec185d45'
down_revision = '6e167aed2b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aidrequest',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('first_ans', sa.Text(), nullable=True),
    sa.Column('second_ans', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aidrequest')
    # ### end Alembic commands ###
