"""Initial migrate

Revision ID: 6e167aed2b8c
Revises: 
Create Date: 2026-06-09 23:09:53.284309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e167aed2b8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('seenStatus', sa.Boolean(), nullable=True),
    sa.Column('specstatus', sa.Boolean(), nullable=True),
    sa.Column('specurl', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_title'), ['title'], unique=False)

    op.create_table('spec',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('course_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spec', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spec_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spec', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_name'))

    op.drop_table('spec')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_title'))

    op.drop_table('course')
    # ### end Alembic commands ###
